### ISSUE TITLE
Ideas for Enhancment

### ISSUE THREAD

**Issue by joh-klein** [LeonGeorgi/RudolstadtForiOS#6]
Hi,
My wife and I used your app exclusively for this years festival. We really liked it!
If you don't mind, I have some suggestions for future updates:

- possibility to enlarge the artists picture (pinch to zoom) – my wife constantly took screenshots of the artist view to be able to more closely look at the artists pictures
- it would be super useful, if the map of the location could be enhanced (zoomed in)
- instead of Apple Maps it might be better to use OpenStreetMap because the map material for such a small town is much better
- maybe there could be a way to share with someone else what event we are at? We met a friend there and I was constantly copying location names and artist names into SMS – it has to be rather low-tech, since no data connection was possible during the day (sending SMS or calling was fine though): Example: "We are here: [Artist Name], [Location], [Event start time]"

Once again: we really appreciated your app! Thank you!

**Comment by LeonGeorgi** [comment]
Thank you very much for the nice feedback. I received a couple of mails thanking me for the app, but people basically didn't give me helpful feedback what to improve. So I'm really glad about this feedback about small things that could be improved. If you have more, please add more! 🙂

I'll try to improve some of the things. I'm not completely sure if a switch to OpenStreetMap would be easy, because using Apple Maps is super easy with Swift and SwiftUI. But I agree that it might be a bit better.

But I'll put all of the other things on my list for next year. And OpenStreetMap with a question mark.

> - it would be super useful, if the map of the location could be enhanced (zoomed in)

You mean in the detail view of a stage?

**Comment by LeonGeorgi** [comment]
I created several issues for the individual ideas now.
